### ISSUE TITLE
How can I post image with reply

### ISSUE THREAD

**Issue by IPreferPrivacy** [Suleman-Elahi/TwitterAutoReplyBot#10]
Is it supported yet?

**Comment by Suleman-Elahi** [comment]
It is possible.

Replace `api.update_status(status=m, in_reply_to_status_id = s.id)` with `api.update_status_with_media(status=m, in_reply_to_status_id = s.id, imagePath)`.

See the extra `imagePath` parameter. Set it to the path of the image you want to use.
