### ISSUE TITLE
Do i need to apply for Elevated Access?

### ISSUE THREAD

**Issue by peebeekay** [Suleman-Elahi/TwitterAutoReplyBot#12]
So i am new to all of this but i followed the instructions and when i go to run it i get this message 

"453 - You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve

C:\Users\whati\Desktop\TwitterAutoReplyBot-master (1)\TwitterAutoReplyBot-master>"C:\Users\whati\Desktop\TwitterAutoReplyBot-master (1)\TwitterAutoReplyBot-master\bot.py""

Does this mean i screwed up or do i need to apply for Elevated Access to be able to run this python file? Any help would be greatly appreacited! And this goes without saying and I know i havent actually got to use this python script yet but holy crap you did an amazing job with this! This is exactly what i was looking for!!!

**Comment by Suleman-Elahi** [comment]
It's been 5 years since I created this script for personal use and at that time there was no such thing as elevated access. They have introduced this last year I guess, so yes you will have to apply for elevated access afaik. I don't know why I didn't see this issue so sorry for delay.
